// update the component versions for each release
:fuse-version: 7.4

// URLs
:openshift-console-url: {openshift-host}/console
:fuse-url: https://eval.apps.city.openshiftworkshop.com/
:route: https://wt3-{user-username}-3scale.{openshift-app-host}

//attributes
:title: Low-code API development and SaaS integration
:standard-fail-text: Verify that you followed all the steps. If you continue to have issues, contact your administrator.

[id='3-low-code-api-development']
= {title}

// word count that fits best is 15-22, with 20 really being the sweet spot. Character count for that space would be 100-125
Learn how to implement a container-native OpenAPI RESTful API without coding.

Container-native applications::
Applications that are designed to run in a containerised environment.

// This is taken right from https://github.com/OAI/OpenAPI-Specification
OpenAPI Specification::
A standard, programming language-agnostic interface description for REST APIs. REST APIs allow both humans and computers to discover and understand the capabilities of a service without requiring access to source code, additional documentation, or inspection of network traffic. When properly defined via OpenAPI, a consumer can understand and interact with the remote service with a minimal amount of implementation logic.

In this Solution Pattern you follow a design-first approach, based on the OpenAPI specification, to define a RESTful API that accepts a name parameter and echoes it back in the response body.
You then use the resulting Open API definition to generate the code for your API and deploy it in a containerised environment.

Following a design first approach to API development is self-documenting, and provides a clear API definition for partners and end-users of your API.
It also allows you to identify important design decisions prior to coding and deployment.

[type=walkthroughResource,serviceName=openshift]
.Red Hat OpenShift
****
* link:{openshift-console-url}[Console, window="_blank"]
****

[type=walkthroughResource,serviceName=fuse]
.Red Hat Fuse Online
****
* link:{fuse-url}[Console, window="_blank"]
****

:sectnums:

[time=20]
== Creating a Slack Connection in Fuse Online

In Fuse Online a *Connection* holds the information required to connect to a service.
For example, a Slack *Connection* in Fuse Online requires an *API Token* and *Slack URL* to function.

=== Creating a Slack Workspace
:context: creating-slack-connection
.Prerequisite
You already have an account with link:https://slack.com/[Slack, window="_blank", id="{context}-1"].

.Procedure
. Navigate to the link:https://slack.com/create[Create a new workspace, window="_blank", id="{context}-2"] page.

. Enter your email address and click *Next*.
Complete the Slack log in process.

. When prompted *What's the name of your company or team?* enter::
+
----
low-code-workspace
----

. When prompted *What’s a project your team is working on?* enter:
+
----
low-code-demo
----

. Click *Skip for now* when prompted to add team members.
. Answer the follow-up questions related to your workspace and choose the *Free* plan.
. Click *Launch My Workspace* when prompted.

[type=verification]
Can you access your workspace, and navigate to the *low-code-demo* channel listed on the left of the workspace?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, check your email, there may be information sent to you about accessing your workspace.


=== Creating the Slack Connection in Fuse Online

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-3"] console.
+
NOTE: This is your personal Fuse Online instance and not the shared instance available from link:/[home page, id="{context}-4"].

. Choose *Connections* from the left navigation menu.

. Click the *Create Connection* button in the top right corner.

. Choose *Slack* from the list of displayed *Connectors*.
You are prompted for configuration details.

. Obtain a URL for the *Slack Webhook URL* field:
.. Navigate to the Slack Apps portal at link:https://api.slack.com/apps[api.slack.com/apps, window="_blank", id="{context}-5"].
.. Click *Create an App*.
.. Enter the following in the *App Name* field:
+
----
Fuse Online Demo
----
.. Choose *low-code-workspace* from the *Development Slack Workspace* dropdown.
.. Click "Create App".
.. On the following screen under the *Add features and functionality* click *Incoming Webhooks*.
.. Change the *Activate Incoming Webhooks* switch to the *On* position.
.. Scroll down and click *Add New Webhook to Workspace*.
.. Select *low-code-demo* in the *Where should Fuse Online Demo post?* field and click *Allow*.
+
You are redirected back to the *Incoming Webhooks* page.
.. Copy the *Webhook URL* displayed at the bottom of the page using the *Copy* button.

. Paste the copied *Webhook URL* value into the *Slack Webhook URL* field in Fuse Online.

. Obtain a value for the *Token for Accessing Slack API* field:
.. Navigate to the Slack API Token portal at link:https://api.slack.com/custom-integrations/legacy-tokens[api.slack.com/custom-integrations/legacy-tokens, window="_blank", id="{context}-6"].
.. Scroll down to the *Legacy token generator* section.
.. Click *Create token* button next to *low-code-workspace*.
.. Copy the generated token.

. Paste the generated token into the *Token for Accessing Slack API* field in Fuse Online.

. Enter the following in the *Sending User Name for Messages* field:
+
----
Fuse Online
----

. Click *Validate* in Fuse Online and verify that a *Slack has been successfully validated.* message appears.
This validation sends a message to the *low-code-demo* channel.

. Click *Next*.

. Enter the following in the *Name* field on the *Name connection* screen:
+
----
Greeting Slack Target
----

. Click *Save*.

[type=verification]
Is a *Greeting Slack Target* entry listed in the Fuse Online *Connections* screen?

[type=verificationFail]
{standard-fail-text}

[time=20]
== Creating an API Integration in Fuse Online

=== Creating an Integration with API details
:context: creating-api-integration
In this procedure, you create an integration with an API and include a data type.
A *Data Type* represents a data structure that can be passed to your API and can then be used as parameters in your API definition and within the Fuse Online *Integration Flow Editor* to transform and map data as part of an *Integration*.

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-1"] console.

. Choose *Integrations* from the left navigation menu.

. Click the *Create Integration* button to start the *New Integration* wizard.

. Choose *API Provider* on the *Choose a Start Connection* screen.

. When prompted choose *Create*
. Click *Next* to navigate to the *Provide API Definition* screen.

. Rename your API from "Untitled API" to:
+
----
Greeting API
----

. Edit the *Description* in the *Design* tab on the right in the *INFO* section:
+
----
My greeting API
----

. Click *Add a data type* under the *Data Types* heading on the left of the *API Designer* screen.

. In the *Enter Basic Information* section enter the following in the *Name* field:
+
----
Name
----

. Enter the following JSON in the *Enter JSON Example* field:
+
[subs="attributes+"]
----
{
    "name": "shadowman"
}
----

. Make sure *No Resource* is selected in the *Choose to create a REST Resource with the Data Type* section.
. Scroll down and click *Save*.

[type=verification]
Is `</> Name` listed under the *Data Types* on the *Provide API Definition* screen?


[type=verificationFail]
{standard-fail-text}


=== Creating a POST Resource Path

A *Path* represents an API endpoint/operation and the associated parameters required to invoke it.

. Click *Add a path* under the *Paths* heading of the *Provide API Definition* screen.

. In the window that appears, enter the following in the *Path* field:
+
----
/greeting
----

. Click *Add* to confirm your entry.

. Click your new */greeting* endpoint under the *Paths* heading.

. Select the *POST* tab in the *Operations* section, and click *Add Operation*.

. Enter the following in the *Summary* field:
+
----
Greet with name
----

. Enter the following in the *Operation ID* field:
+
----
greetname
----

. In the *Request Body* section, click *Add a request body*.

. Choose *Name* as the type.

. In the *Responses* section click *Add a response*.
.. In the window that appears choose *200 OK* as the option.
.. Click *Add*.
.. Click *No description* beside the *200 OK* response and enter the following in the *Description* field:
+
----
Greeting response
----
.. Choose *String* as the type.
Fuse Online automatically completes the type *String as String*.


. Click *Save* in the top right corner of the page to save your work.
The *Review Actions* screen of the *New Integration* wizard is displayed.

. Click *Next*.

. Click *Save* on the *New Integration* wizard screen.

. On the *Save the integration* screen:
.. Enter the following in the *Name* field:
+
[subs="attributes+"]
----
Greeting Integration {user-username}
----
.. Enter the following in the *Description* field:
+
----
my greeting api
----

. Click *Save* to save your API design.


[type=verification]
Is a *Greet with name* entry listed in the *Operations* screen?

[type=verificationFail]
{standard-fail-text}
