[time=5]
== Creating connections
:context: creating-connections

// tag::creating-api-connector[]

[id='creating-api-connector_{context}']
[.integr8ly-docs-header]
=== Creating an API Connector

Fuse Online is an enterprise integration platform that provides connectors for many services, such as Gmail and IRC.
You can extend Fuse Online with custom connectors, using either OpenAPI definitions (Swagger) or JAR files.
To create a connector for the Fuse RESTful API, register the OpenAPI definition as a *Customization*:

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-1"] console.
+
NOTE: You are not logging into the shared Fuse Online instance, available from the link:/[All services tab].
Starting this Solution Pattern provisioned an instance of Fuse Online which is not shared with other cluster users.

. Select *Customizations > API Client Connectors* from the left hand menu.

. Select the *Create API Connector* button to start the *API Client Connector* wizard.

. When prompted to *Upload OpenAPI Document*, select *Use a URL*:
.. Enter the following in the URL field:
+
[subs="attributes+", id="route-crud-host-url-connector"]
----
{route-orders-fuse-api-host}/openapi.json
----
This OpenAPI (swagger) file defines the API for querying and creating orders in the underlying PostgreSQL database.

.. Click *Next*.

. When prompted with *Review Actions*, select *Next*.

. When prompted with *Specify Security*, select *Next*.

. When prompted with *Review/Edit Connector Details*:
.. Enter the following in the *Name* field:
+
[subs="attributes+"]
----
Order System REST API Connector
----

.. Click *Save*.

[type=verification]
Is the new connector *Order System REST API Connector* displayed on the *Customizations > API Client Connectors* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-2"] console?

[type=verificationFail]
{standard-fail-text}

// end::creating-api-connector[]


// tag::creating-http-connection[]

[id='creating-http-connection-in-fuse_{context}']
[.integr8ly-docs-header]
=== Creating HTTP connection to CRUD App

To enable Fuse Online to send messages from the queue to the Order Management System, create a connection in Red Hat Fuse Online using the API connector you created earlier.


. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-3"] console.

. Select *Connections* from the left hand menu.

. Select the *Create Connection* button to start the *Create Connection* wizard.

. When prompted with *Select connector*, select *Order System REST API Connector*.

. When prompted with *Configure connection*:
.. Enter the following in the *Host* field:
+
[subs="attributes+", id="route-crud-host-url"]
----
{route-orders-fuse-api-host}
----
This is the location of the *rhmi-lab-internal-fuse-api* application that was created by the API Connector above

.. Enter a forward slash, that is, `/`, in the *Base path* field and click *Next*

. When prompted with *Name connection*:
.. Enter the following in the *Name* field:
+
----
Order System REST API Connection
----
.. Click *Save*.


[type=verification]
Is the new connection displayed on the *Connections* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-4"] console?

[type=verificationFail]
{standard-fail-text}


// end::creating-http-connection[]

[id='creating-amqp-connection-in-fuse_{context}']
[.integr8ly-docs-header]
=== Creating an AMQP connection in Red Hat Fuse Online

To allow Fuse Online to consume messages placed on the queue by the Order Entry System, create a connection in Red Hat Fuse Online:


:fuse-url: https://eval.apps.city.openshiftworkshop.com/
:openshift-url: https://master.city.openshiftworkshop.com/console/project/eval/overview
:enmasse: AMQ Online

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-5"] console.

. Select *Connections* from the left hand menu.

. Select the *Create Connection* button to start the *Create Connection* wizard.

. Select *AMQP Message Broker* to configure an *AMQP* connection.

. Enter the connection URI relating to {enmasse}:
+
[subs="attributes+"]
----
amqp://{enmasse-broker-url}:5672?amqp.saslMechanisms=PLAIN
----

. Enter the username for {enmasse}:
+
[subs="attributes+"]
----
{enmasse-credentials-username}
----

. Enter the password for {enmasse}:
+
[subs="attributes+"]
----
{enmasse-credentials-password}
----

. Set the value of *Check certificates* to `Disable`.

. Select the *Validate* button to check that the values are valid.

. Click *Next* and enter a name for the connection, for example:
+
[subs="attributes+"]
----
Incoming Order Queue Connection
----

. Click *Save*.


[type=verification]
Is the new connection displayed on the *Connections* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-6"] console?


[type=verificationFail]
{standard-fail-text}


// end::creating-amqp-connection-in-fuse[]

[type=taskResource]
.Task Resources
****
* link:https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/html-single/integrating_applications_with_fuse_online/connecting-to-applications_ug#about-creating-connections_connections[About creating connections from Fuse Online to applications, window="_blank"]
* link:https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/html-single/connecting_fuse_online_to_applications_and_services/#supported-connectors_connectors[Connectors that are supported by Fuse Online, window="_blank"]
* link:https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol[About AMQP, window="_blank"]
****
