[time=5]
[#creating-a-table]
==  Creating a table
:context: creating-a-table

To create a table for storing the orders, you will use PostgreSQL.

. Log into link:{openshift-host}/console/project/{walkthrough-namespace}/overview[OpenShift Namespace, window="_blank"] for this walkthrough.
. Select *Applications > Pods* from the left hand menu.
. Click the Pod that has the name *rhmi-lab-orders-db* followed by an ID, for example *rhmi-lab-orders-db-1-cfqh2*.
. Select the *Terminal* tab on the Pod details screen.
. Log in to the *orders* database using the command:
+
[subs="attributes+"]
----
psql -U {user-username} -W -d orders
----
. Enter the following when prompted:
+
[subs="attributes+"]
----
password
----
+
For security reasons, the password is not shown in the terminal.
Paste the password then press the *Enter* key.

. Paste the following as SQL to create the `received_orders` table:
+
[subs="attributes+"]
----
CREATE TABLE received_orders (
  id serial PRIMARY KEY,
  product text NOT NULL,
  quantity int NOT NULL,
  message_id text NOT NULL,
  datetime timestamp NOT NULL
);
----

[type=verification]
Is the `received_orders` table listed when you enter the `\d` command in the terminal for the PostgreSQL pod?

[type=verificationFail]
{standard-fail-text}

// end::task-table-setup[]
