[time=5]
[#creating-an-integration]
== Creating an integration
:context: creating-an-integration

// end::task-creating-fuse-integration[]


To use the Fuse connections, create an integration in Red Hat Fuse Online:

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="wt1a_2_3_1_fuse-url"] console.

. Select *Integrations* from the left hand menu.

. Select the *Create Integration* button to start the *Create Integration* wizard.

. Choose *Incoming Order Queue Connection* as the *Start Connection*.

. When prompted to *Choose an action*, select *Subscribe for messages* and click the *Select* button.

. When prompted for a *Destination name*, enter:
+
[subs="attributes+"]
----
work-queue-requests
----

. Choose *Queue* as the *Destination type* and click *Next*.

. When prompted to *Specify Output Data Type*:
.. Select *JSON Schema* as the type.
.. Enter the following in the *Definition* field:
+
[subs="attributes+"]
----
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"product": {
			"type": "string"
		},
		"quantity": {
			"type": "number"
		},
		"datetime": {
			"type": "string"
		},
		"message_id": {
			"type": "string"
		}
	}
}
----
.. Click *Next*.

. Choose *Order System REST API Connection* as the *Finish Connection*.

. When prompted to *Choose an action*, select *Create an order* and click the *Select* button.

. When prompted with *Configure the action* click *Next*.

. When prompted to *Add to Integration*, click on the blue *+* icon between the *Subscribe for messages* and *Create an order* elements.

. Select *Data Mapper* to map source and target fields in the corresponding JSON schemas:
.. Expand the *body* item in the *Target* tree.
.. Click and drag *datetime*, *message_id*, *product*, and *quantity* from the *Source* column to their corresponding locations under *body* in the *Target* column.
.. Click *Done* to navigate back to the *Integration* screen.

. Click *Publish*.
. When prompted, enter a name, for example:
+
[subs="attributes+"]
----
Walkthrough 1A
----
. Click *Save and publish*.

. Monitor the *Integration Summary* dashboard until a green check mark is displayed beside the new integration.
The integration may take some time to complete building.

[type=verification]
Is the integration displayed as *Running* on the *Integrations* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank", id="{context}-1"] console?

[type=verificationFail]

****
. Wait for the integration to appear. This can take several minutes.

. Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
****
// end::task-creating-fuse-integration[]


[type=taskResource]
.Task Resources
****
* https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/html-single/integrating_applications_with_fuse_online/creating-integrations_ug#creating-integrations_ug[Creating integrations, window="_blank"]
****
